---
title: "Final"
author: "Antonio Pano Flores"
date: "3/9/2021"
output: html_document

---
```{r}
library(readxl)
library(tidyr)
library(dbplyr)
library(ggplot2)
```

```{r}

DATA  = read_excel("stor 538 playoffs round 1 archery data.xlsx")


DATA = DATA[,-c(1)]
DATA = DATA[,c(1:23)]
DATA = na.omit(DATA)

DATA$`Eyes Open` = as.factor(DATA$`Eyes Open`)
head(DATA)
```


```{r}
Model = lm(Points ~ `Time to Shoot (s)`+ `Eyes Open`+ Blinks + Gender, data = DATA)
summary(Model)


Model1 = lm(DATA$Points ~ DATA$`Time to Shoot (s)`)
Model2 = lm(DATA$Points ~ DATA$`Eyes Open`)
Model3 = lm(DATA$Points ~ DATA$Blinks)

print("YO YO YO")
#summary(Model1)
#summary(Model2)
#summary(Model3)
BackwardModel = step(Model, direction = "backward")
```


```{r}
plot(jitter(Points) ~ `Time to Shoot (s)`+ `Eyes Open`+ Blinks, data = DATA, ylab="Points", col = 2:21)


ggplot(data = DATA, mapping = aes(x = DATA$`Time to Shoot (s)`, y = jitter(DATA$Points))) + geom_point(colour = "black", shape = 21, size = 3) + theme_classic() + xlab("Time To Shoot (seconds)") + ylab("Points") 

summary(BackwardModel)
```


```{r}
DATA$`Eyes Open` = as.numeric(DATA$`Eyes Open`)
DATA$Gender = as.numeric(as.factor(DATA$Gender))


DATA$Gender = ifelse(DATA$Gender == 1, 0, ifelse(DATA$Gender == 2, 1, 3))


plot(jitter(Points) ~ `Time to Shoot (s)`, data = DATA, ylab="Points", col = 2:21, xlab = "`Time to Shoot (s)` + `Eyes Open` + Gender")
par(new=TRUE)
plot(jitter(Points) ~ `Eyes Open`, data = DATA, ylab="Points", col = 2:21, xlab = "`Time to Shoot (s)` + `Eyes Open` + Gender")
par(new = TRUE)
plot(jitter(Points) ~ Gender, data = DATA, ylab="Points", col = 2:21,xlab = "`Time to Shoot (s)` + `Eyes Open` + Gender")
abline(BackwardModel)
axis(labels = "yea", at = 1, side = "1")
```



```{r}
last = lm(Points ~ poly(`Time to Shoot (s)`,4), data = DATA)
summary(last)


ggplot(data=DATA,aes(DATA$`Time to Shoot (s)`, jitter(DATA$Points))) + geom_point(colour = "deepskyblue3", shape = 21, size = 3) + 
   geom_smooth(method = "lm", formula = y ~ poly(x, 2)) + theme_update() + xlab("Time To Shoot (seconds)") + ylab("Points") +   scale_color_identity()
```
